# Generated by Django 5.2.3 on 2025-07-24 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNIVERSITY', '0003_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField(help_text='The start date of the pay period.')),
                ('pay_period_end', models.DateField(help_text='The end date of the pay period.')),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Total earnings before deductions.', max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Total deductions (e.g., taxes, benefits).', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Earnings after all deductions.', max_digits=10)),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this payroll was processed.')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this payroll.', null=True)),
                ('employee', models.ForeignKey(help_text='The employee associated with this payroll record.', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='UNIVERSITY.employee')),
            ],
            options={
                'verbose_name': 'Payroll Record',
                'verbose_name_plural': 'Payroll Records',
                'ordering': ['-pay_period_end', 'employee__last_name', 'employee__first_name'],
                'unique_together': {('employee', 'pay_period_start', 'pay_period_end')},
            },
        ),
    ]
