# Generated by Django 5.2.3 on 2025-07-24 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNIVERSITY', '0004_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique identifier for the student (e.g., matriculation number).', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, help_text='The date the student enrolled in the university.')),
                ('major', models.CharField(blank=True, help_text="The student's primary field of study.", max_length=100, null=True)),
                ('current_year', models.IntegerField(default=1, help_text='The current academic year the student is in (e.g., 1 for Freshmore, 4 for Senior).')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the student record is active.')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name', 'student_id'],
            },
        ),
    ]
